### ISSUE TITLE
Some problem of freej2me on minijvm

### ISSUE THREAD

**Issue by vad0sss** [digitalgust/freej2meOnMinijvm#1]
Can you please tell me how to implement it in AppManager miniJVM?

**Comment by vad0sss** [comment]
Can you post the build script?

**Comment by digitalgust** [comment]
IDE idea open the project , modify dependent jar path, build project in idea, and install the jar to appmanager

**Comment by vad0sss** [comment]
Hello, some games have the ability to enter text using the TextField class, but it does not work for you.

**Comment by digitalgust** [comment]
the first version for games, it will take some time to fix the TextField

**Comment by digitalgust** [comment]
fixed textfield, textbox, input supported

**Comment by vad0sss** [comment]
> fixed textfield, textbox, input supported

Thank you.
It seems to me that there is still a problem with the RMS, when the game starts, the RMS starts loading and the window crashes.
Link to the game: https://ru.files.fm/f/672fnp6wn

**Comment by digitalgust** [comment]
fix jvm ret jsr instruction, that's crash cause.
<img width="676" alt="iShot_2023-04-29_09 52 07" src="https://user-images.githubusercontent.com/19265420/235278170-7facdd01-af91-4f89-b408-b4f95ec95199.png">

**Comment by vad0sss** [comment]
@digitalgust Thank you!
